const LIMITATIONS_HEADING = '연구의 한계점';
const APPLICATION_HEADING = '실생활 적용법';
const FAQ_HEADING = '자주 묻는 질문(FAQ)';
const READER_ENDINGS = [LIMITATIONS_HEADING, APPLICATION_HEADING, FAQ_HEADING];
function hasReaderSections(article) {
    const headings = (article?.sections || []).map(s => s.heading.trim());
    return READER_ENDINGS.every((heading, index) =>
        headings.filter(h => h === heading).length === 1 && headings[headings.length - 3 + index] === heading);
}

const WRITE_STYLE = `Reader-facing Korean must be understandable to a middle-school student without science training. Use familiar words, active verbs and short sentences, usually one idea per sentence. Use 2-3 short sentences per paragraph and avoid long noun chains or literal academic translations. Keep combined paragraphs within 1000-2500 characters; prefer a concise complete explanation to filling the upper limit. Explain any necessary technical term immediately in everyday words. Prefer "여러 연구 결과를 모아 비교했습니다" to unexplained "네트워크 메타분석", and "몸속 염증 상태를 살펴보는 수치" to unexplained "염증 바이오마커". Avoid unexplained English abbreviations, statistical notation and lists of numbers; include only numbers that help answer the reader's question, without losing accuracy. Never pad the required length with repetition.
Explain the study's actual findings directly and within their scope. Include the study population and design early. Keep conditions essential to interpreting a particular result next to it (for example, an animal experiment or a measured marker rather than disease recovery). Preserve association versus causation and never turn uncertain evidence into an established benefit.
End with exactly these three separate sections, in this order: "${LIMITATIONS_HEADING}", "${APPLICATION_HEADING}", "${FAQ_HEADING}". Gather study duration, evidence certainty, differences between studies, generalizability and missing clinical outcomes in the limitations section, using concrete, plain-language explanations tied to the relevant findings. Outside that section, use at most one brief qualification about the study's overall scope, near the opening result. Do not append "단정할 수 없습니다", "뜻은 아닙니다", "알 수 없습니다", "주의가 필요합니다" or "더 많은 연구가 필요합니다" to every explanation. Do not explain the same marker, study design or population repeatedly to fill space. A single clearly organized limitations section is sufficient; repeat a qualification elsewhere only when omitting it would make that specific statement misleading. The separate limitations section cannot repair an overstated title or summary.
In "${APPLICATION_HEADING}", give 2-3 specific, feasible actions connected to the topic, using familiar verbs and examples. Help readers decide what to do today, what to check, and how to tell they completed the action. Avoid empty advice like "기억하세요" or repeating the study conclusion. For food studies, practical meal ideas are allowed when the supplied evidence supports them. If the study does not justify changing consumption, give useful decision skills such as comparing the studied ingredient/form with a label or preparing a specific question, rather than inventing a benefit, dose or purchase recommendation. Do not equate an extract or supplement with the same amount of ordinary food. Reader agency means a clear achievable next step, not promising efficacy beyond the study.
In "${FAQ_HEADING}", answer 2-4 real reader questions about daily decisions or common misunderstandings. Each paragraphs item must contain ONE pair in exactly this format: "Q. 질문\\nA. 짧고 직접적인 답변" (actual newline between Q and A). Answers should lead with the useful answer, then only the essential explanation. Do not simply repeat the limitations or all previous paragraphs. All practical actions and FAQ factual claims must be supported by the supplied material; do not invent diet rules, treatment advice or personal doses.`;

const REVIEW_STYLE = `Editorial policy: uncertainty MUST be collected in the dedicated "${LIMITATIONS_HEADING}" section. If that section correctly explains the certainty of the named findings, NEVER demand that certainty or a clinical-benefit disclaimer again in a results paragraph. Directly reporting that a measured marker was lower IN THE STUDY is permitted; it does not claim a proven health benefit. Essential local context means actual scope errors such as reporting animal results as human results, or a correlation as proven prevention/treatment, not repeating the certainty rating. Reject real scope errors and overstated titles even if later cautions exist.
Review the WHOLE article for a middle-school reading level. Flag actual unexplained jargon, complicated sentences or repeated defensive boilerplate. Check the separate practical application section for concrete feasible actions, and the FAQ for useful direct answers. Practical actions can teach label comparison or informed decision-making without claiming a new clinical benefit; distinguish these procedural suggestions from factual health claims. Reject invented benefits, food-extract equivalence, personal doses or unsupported dietary rules in either section. A short scope clarification answering a specific FAQ question is permitted and need not repeat every limitation. Report objective factual errors, unsupported health claims and concrete readability defects; do not fail correct text because of a hypothetical reader's worst possible interpretation or a preferred academic synonym. Simple general explanations of research terms do not imply that every trial used identical procedures. A focused article need not list every statistic or every result in the paper. A summary need not enumerate every supplement named in the body. A plain explanation of what was measured need not include technical molecular classifications, provided it does not misclassify or falsely equate substances. Put optional alternative wording in warnings, not issues.`;

module.exports = { LIMITATIONS_HEADING, APPLICATION_HEADING, FAQ_HEADING, hasReaderSections, WRITE_STYLE, REVIEW_STYLE };
