const LIMITATIONS_HEADING = '연구의 한계점';

const WRITE_STYLE = `Reader-facing Korean must be understandable to a middle-school student without science training. Use familiar words, active verbs and short sentences, usually one idea per sentence. Use 2-3 short sentences per paragraph and avoid long noun chains or literal academic translations. Explain any necessary technical term immediately in everyday words. Prefer "여러 연구 결과를 모아 비교했습니다" to unexplained "네트워크 메타분석", and "몸속 염증 상태를 살펴보는 수치" to unexplained "염증 바이오마커". Avoid unexplained English abbreviations, statistical notation and lists of numbers; include only numbers that help answer the reader's question, without losing accuracy. Never pad the required length with repetition.
Explain the study's actual findings directly and within their scope. Include the study population and design early. Keep conditions essential to interpreting a particular result next to it (for example, an animal experiment or a measured marker rather than disease recovery). Preserve association versus causation and never turn uncertain evidence into an established benefit.
Include exactly one section headed "${LIMITATIONS_HEADING}" near the end. Gather study duration, evidence certainty, differences between studies, generalizability and missing clinical outcomes there, using concrete, plain-language explanations tied to the relevant findings. Do not repeat defensive boilerplate such as "단정할 수 없습니다", "주의가 필요합니다" or "더 많은 연구가 필요합니다" in every paragraph. A single clearly organized limitations section is sufficient; repeat a qualification elsewhere only when omitting it would make that specific statement misleading. The separate limitations section cannot repair an overstated title or summary. Practical takeaways must remain evidence-grounded.`;

const REVIEW_STYLE = `Also review readability: the title, summary and body should be understandable to a middle-school student, with necessary scientific terms explained in everyday Korean. Flag concrete examples of unexplained jargon or needlessly complicated sentences for correction. Evaluate limitations across the WHOLE article, including its dedicated "${LIMITATIONS_HEADING}" section. Do not require the same caution or limitation in every paragraph. Do require essential result-specific context when omission would mislead, and reject overstated titles or summaries even if later cautions exist. A focused article need not list every statistic or every result in the paper; omitted results are defects only when the omission makes what the article actually says misleading. Do not request extra technical detail solely because it exists in the paper.`;

module.exports = { LIMITATIONS_HEADING, WRITE_STYLE, REVIEW_STYLE };
